### ISSUE TITLE
Get a working publish process (primarily for TGS)

### ISSUE THREAD

**Issue by Cyberboss** [OpenDreamProject/OpenDream#1495]
Mainly for TGS to minimize the amount of work it has to do and thus be more forwards compatible

Current TGS build process (translated from C# to shell):
```
dotnet build -c Release /p:TgsEngineBuild=true
mv bin/Content.Server <instance install path>/bin/server
mv bin/DMCompiler <instance install path>/bin/compiler
mv RobustToolbox/Resources <instance install path>/RobustToolbox/Resources
```

Ideal TGS build process:
```
dotnet publish -c Tgs -o <instance install path>
```

Which builds some directory structure similar to the one described above or, ideally, something more optimized

**Comment by Cyberboss** [comment]
It's odd that the server executable has to be in `bin/Content.Server`
```
    [FATL] unhandled: System.IO.DirectoryNotFoundException: Specified directory does not exist: C:\USERS\DOMINION\APPDATA\LOCAL\TEMP\TGS_INTEGRATION_TEST\1F4B894C-DE43-4110-BCEC-20CB1B743793\INSTANCE-ODTESTSINSTANCE\Byond\OpenDream-2698cabf07a1a2a422422d940a977fb024384a6b-1\bin\Content.Server\
   at Robust.Shared.ContentPack.ResourceManager.MountContentDirectory(String path, Nullable`1 prefix) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Shared\ContentPack\ResourceManager.cs:line 146
   at Robust.Shared.ProgramShared.DoMounts(IResourceManagerInternal res, MountOptions options, String contentBuildDir, ResPath assembliesPath, Boolean loadContentResources, Boolean loader, Boolean contentStart) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Shared\ProgramShared.cs:line 60
   at Robust.Server.BaseServer.Start(ServerOptions options, Func`1 logHandlerFactory) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\BaseServer.cs:line 300
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\Program.cs:line 68
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.StartLibrary(String[] args, ServerOptions options) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\ContentStart.cs:line 16
   at OpenDreamServer.Program.Main(String[] args) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\OpenDreamServer\Program.cs:line 7
Unhandled exception. System.IO.DirectoryNotFoundException: Specified directory does not exist: C:\USERS\DOMINION\APPDATA\LOCAL\TEMP\TGS_INTEGRATION_TEST\1F4B894C-DE43-4110-BCEC-20CB1B743793\INSTANCE-ODTESTSINSTANCE\Byond\OpenDream-2698cabf07a1a2a422422d940a977fb024384a6b-1\bin\Content.Server\
   at Robust.Shared.ContentPack.ResourceManager.MountContentDirectory(String path, Nullable`1 prefix) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Shared\ContentPack\ResourceManager.cs:line 146
   at Robust.Shared.ProgramShared.DoMounts(IResourceManagerInternal res, MountOptions options, String contentBuildDir, ResPath assembliesPath, Boolean loadContentResources, Boolean loader, Boolean contentStart) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Shared\ProgramShared.cs:line 60
   at Robust.Server.BaseServer.Start(ServerOptions options, Func`1 logHandlerFactory) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\BaseServer.cs:line 300
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\Program.cs:line 68
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\Program.cs:line 46
   at Robust.Server.ContentStart.StartLibrary(String[] args, ServerOptions options) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\RobustToolbox\Robust.Server\ContentStart.cs:line 16
   at OpenDreamServer.Program.Main(String[] args) in C:\a515b512-e3be-44cd-b47d-d9fc21277445\OpenDreamServer\Program.cs:line 7
```
