### ISSUE TITLE
Can't `spawn()` while enumerating a list

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#163]
Code:
```
for(var/mob/M in world)
    spawn(0) M.UpdateClothing()
```

Exception:
```
=C# StackTrace=
System.NotImplementedException: The method or operation is not implemented.
   at OpenDreamRuntime.Procs.DMProcState..ctor(DMProcState other, DreamThread thread) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DMProc.cs:line 160
   at OpenDreamRuntime.Procs.DMProcState.Spawn() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DMProc.cs:line 220
   at OpenDreamRuntime.Procs.DMOpcodeHandlers.Spawn(DMProcState state) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DMOpcodeHandlers.cs:line 1129
   at OpenDreamRuntime.Procs.DMProcState.InternalResume() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DMProc.cs:line 179
   at OpenDreamRuntime.ProcState.Resume() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\DreamThread.cs:line 76
```

**Comment by wixoaGit** [comment]
This was fixed in 436390335973c148c36413b898df7b88976898b6 once it was realized that an enumerator is never going to be enumerated inside a spawned proc state, leaving no need to copy them.
