### ISSUE TITLE
Adding the same verb proc to `verbs` multiple times causes a runtime warning

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#165]
Code:
```
src.verbs += /mob/proc/mute
src.verbs += /mob/proc/mute
```
Exception:
```
=C# StackTrace=
System.ArgumentException: An item with the same key has already been added. Key: mute
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OpenDreamRuntime.DreamConnection.UpdateAvailableVerbs() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\DreamConnection.cs:line 141
   at OpenDreamRuntime.DreamConnection.set_MobDreamObject(DreamObject value) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\DreamConnection.cs:line 68
   at OpenDreamRuntime.Objects.MetaObjects.DreamMetaObjectClient.OnVariableSet(DreamObject dreamObject, String variableName, DreamValue variableValue, DreamValue oldVariableValue) in C:\Users\main\Documents\GitHub\OpenDream\OpenD
ream\OpenDreamRuntime\Objects\MetaObjects\DreamMetaObjectClient.cs:line 44
   at OpenDreamRuntime.Objects.DreamObject.SetVariable(String name, DreamValue value) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Objects\DreamObject.cs:line 111
   at OpenDreamRuntime.Procs.DreamProcIdentifierVariable.Assign(DreamValue value) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DreamProcIdentifier.cs:line 32
   at OpenDreamRuntime.Procs.DMOpcodeHandlers.Assign(DMProcState state) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DMOpcodeHandlers.cs:line 20
   at OpenDreamRuntime.Procs.DMProcState.InternalResume() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\Procs\DMProc.cs:line 179
   at OpenDreamRuntime.ProcState.Resume() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamRuntime\DreamThread.cs:line 76

```

**Comment by wixoaGit** [comment]
As of #1054 this no longer crashes. It does leave a warning like this in the console though:
`[WARN] root: User "localhost@JoeGenero" has multiple verb commands named "cmd_admin_delete", ignoring all but the first`

This should instead be silent when it's the same proc added twice.
