### ISSUE TITLE
Nebula: send_rsc causes IndexOutOfRangeException

### ISSUE THREAD

**Issue by out-of-phaze** [OpenDreamProject/OpenDream#1748]
```js
[15:00:00] Runtime in code/modules/client/preference_setup/background/01_species.dm,62: Index was outside the bounds of the array.
  Exception occurred: Index was outside the bounds of the array.
  =DM StackTrace=
   /datum/category_item/player_setup_item/background/species/content code/modules/client/preference_setup/background/01_species.dm:62
   /datum/category_group/player_setup_category/background_preferences/content code/modules/client/preference_setup/preference_setup.dm:21
   /datum/category_collection/player_setup_collection/content code/modules/client/preference_setup/preference_setup.dm:103
   /datum/preferences/get_content code/modules/client/preferences.dm:222
   /datum/preferences/open_setup_window code/modules/client/preferences.dm:232
   /mob/new_player/Topic code/modules/mob/new_player/new_player.dm:96
   /client/Topic Types/Client.dm:69
   /client/Topic code/modules/client/client_procs.dm:108

=C# StackTrace=
  System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OpenDreamRuntime.Objects.DreamIconOperationBlendImage.<>c__DisplayClass4_0.<ApplyToFrame>b__0(PixelAccessor`1 accessor) in C:\Users\User\phaze\OpenDream\OpenDreamRuntime\Objects\DreamIcon.cs:line 415
   at SixLabors.ImageSharp.Image`1.ProcessPixelRows(PixelAccessorAction`1 processPixels)
   at OpenDreamRuntime.Objects.DreamIcon.DrawFrames(Rgba32[] pixels, Int32 firstFrameIndex, List`1 frames, AtomDirection dir) in C:\Users\User\phaze\OpenDream\OpenDreamRuntime\Objects\DreamIcon.cs:line 259
   at OpenDreamRuntime.Objects.DreamIcon.GenerateDMI() in C:\Users\User\phaze\OpenDream\OpenDreamRuntime\Objects\DreamIcon.cs:line 117
   at OpenDreamRuntime.Resources.DreamResourceManager.TryLoadIcon(DreamValue value, IconResource& icon) in C:\Users\User\phaze\OpenDream\OpenDreamRuntime\Resources\DreamResourceManager.cs:line 101
   at OpenDreamRuntime.Procs.DMOpcodeHandlers.BrowseResource(DMProcState state) in C:\Users\User\phaze\OpenDream\OpenDreamRuntime\Procs\DMOpcodeHandlers.cs:line 2263
   at OpenDreamRuntime.DreamThread.Resume() in C:\Users\User\phaze\OpenDream\OpenDreamRuntime\DreamThread.cs:line 223
```
The relevant DM code:
```dm
	var/icon/use_preview_icon = current_species.get_preview_icon()
	if(use_preview_icon)
		send_rsc(user, use_preview_icon, current_species.preview_icon_path)
```

**Comment by wixoaGit** [comment]
This isn't a `send_rsc()` issue, it has something to do with what `/icon` procs were called. The server didn't try actually applying the DMI edits until `send_rsc()` needed it.
