### ISSUE TITLE
Winset assuming a window is a control

### ISSUE THREAD

**Issue by ike709** [OpenDreamProject/OpenDream#246]
```
Error while handling received packet (WinSet): System.Exception: Invalid element "canister"
   at OpenDreamClient.Interface.DreamInterface.HandlePacketWinSet(PacketWinSet pWinSet) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamClient\Interface\DreamInterface.cs:line 250
   at OpenDreamClient.OpenDream.<RegisterPacketCallbacks>b__42_12(PacketWinSet packet) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamClient\OpenDream.cs:line 114
   at OpenDreamClient.Net.ClientConnection.ProcessPackets() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamClient\Net\ClientConnection.cs:line 68
```
![image](https://user-images.githubusercontent.com/5714543/126405679-38220730-05e5-491d-a46c-8f0cf5d88310.png)

**Comment by wixoaGit** [comment]
As of #1033, windows are technically controls (their MAIN element). This should no longer be an issue.
